/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Important: return the modified config
    config.watchOptions = {
      ignored: "**/src/theme/autogenerated-variables.css",
    };
    return config;
  },
  swcMinify: true,
  rewrites: async () => {
    return [
      {
        source: "/presentation/:customPage(.*)",
        destination: "/presentation/:customPage/index.html",
      },
    ];
  },
};

module.exports = nextConfig;
